# Generated by Django 5.2.11 on 2026-02-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_spend_entity_alter_spend_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spend',
            name='price',
        ),
        migrations.AddField(
            model_name='spend',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
