# Generated by Django 5.2.11 on 2026-02-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_spend_price_spend_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
