# Generated by Django 5.2.11 on 2026-02-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_spend_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spend',
            old_name='entity',
            new_name='fullsemi',
        ),
        migrations.AddField(
            model_name='spend',
            name='elements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
