# Generated by Django 5.2.11 on 2026-02-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_entity_spend_fullsemi_spend_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_token',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
