# Generated by Django 5.2.11 on 2026-03-11 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='quotation_images/')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('element', models.CharField(max_length=100)),
                ('core_material', models.CharField(max_length=100)),
                ('finish_material', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('specification', models.TextField(blank=True)),
                ('unit', models.CharField(max_length=50)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='billing.client')),
                ('full_semi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.fullsemi')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.image')),
            ],
        ),
    ]
