# Generated by Django 5.2.11 on 2026-03-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_image_quotationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='billing.qtnclient'),
        ),
    ]
