# Generated by Django 5.2.11 on 2026-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_quotationitem_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=10),
        ),
    ]
