# Generated by Django 5.2.11 on 2026-03-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_payment_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
