# Generated by Django 5.2.11 on 2026-03-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_quotationitem_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
