# Generated by Django 5.2.11 on 2026-04-08 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_quotationitem_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='quotation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spends', to='billing.quotationitem'),
        ),
    ]
