# Generated by Django 5.2.11 on 2026-04-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_spend_quotation_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='billing.client'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='billing.client'),
        ),
        migrations.DeleteModel(
            name='QtnClient',
        ),
    ]
