# Generated by Django 5.2.11 on 2026-04-08 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_quotationitem_client_alter_quotation_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QtnClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=200)),
                ('gst', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_mode', models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('estimate_start_date', models.DateField(blank=True, null=True)),
                ('estimate_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spend',
            name='quotation_item',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='billing.qtnclient'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='billing.qtnclient'),
        ),
    ]
