# Generated by Django 5.2.11 on 2026-04-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_qtnclient_remove_spend_quotation_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='billing.client'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='billing.client'),
        ),
        migrations.AddField(
            model_name='spend',
            name='quotation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spends', to='billing.quotationitem'),
        ),
        migrations.DeleteModel(
            name='QtnClient',
        ),
    ]
