# Generated by Django 5.2.11 on 2026-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_quotationitem_client_alter_quotation_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='estimate_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='estimate_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
