# Generated by Django 5.2.11 on 2026-04-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_quotation_estimate_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='billing.project'),
            preserve_default=False,
        ),
    ]
