# Generated by Django 5.2.11 on 2026-04-10 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_remove_quotationdraft_unique_user_draft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quotationdraft',
            name='unique_user_quotation_draft',
        ),
        migrations.RemoveField(
            model_name='quotationdraft',
            name='quotation_id',
        ),
        migrations.AddConstraint(
            model_name='quotationdraft',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_draft'),
        ),
    ]
