# Generated by Django 5.2.11 on 2026-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_remove_quotationdraft_unique_user_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
