# Generated by Django 5.2.11 on 2026-04-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_alter_spend_floor_alter_spend_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.floortype'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.roomtype'),
        ),
    ]
