# Generated by Django 5.2.11 on 2026-06-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_alter_spend_floor_alter_spend_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
