# Generated by Django 5.2.11 on 2026-06-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_payment_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_locked',
            field=models.BooleanField(default=False),
        ),
    ]
