# Generated by Django 5.2.11 on 2026-06-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_payment_invoice_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_archived',
            field=models.BooleanField(default=False),
        ),
    ]
