# Generated by Django 5.2.11 on 2026-06-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_projectdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdiscount',
            name='description',
        ),
    ]
