# Generated by Django 5.2.11 on 2026-06-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_remove_projectdiscount_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDiscount',
        ),
    ]
